# Generated by Django 5.1.1 on 2024-09-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mealplan', '0001_initial'),
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='recipes',
            field=models.ManyToManyField(to='recipe.recipe'),
        ),
    ]
