# Generated by Django 5.1.1 on 2024-09-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplan', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='shopping_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ShoppingList',
        ),
    ]
